// Ensures the "start" function is only called for when the page has been fully loaded, if this were not the case, errors may be present as the script may attempt to access elements which have not yet been rendered.

window.addEventListener('load', start)

var vehicleSearchForm = document.forms.vehicleSearchForm
var vehicles = getVehicles();
var container = document.getElementById('display-results')
var submitEvent = document.getElementById('submitEvent')
var modal = document.getElementById('modal')
var modalBody = document.getElementById('modalBody')

// Displays the vehicle results which have been filtered by other functions by creating a card (an "article" element) for each vehicle, which is then populated with the relevant information and appended to the container.
// If no vehicles are found matching the search criteria, a message is displayed notifying the user that none were found matching their criteria.
// Calls for the "openModal" function if a card is clicked on, where a modal is then opened with extra information about the vehicle.
// The "openModal" function can also be called by pressing the "Enter" key when a card is selected, for accessibility purposes.

function displayResults(vehicles) {
    container.innerHTML = "";

    if (vehicles.length === 0) {
        container.innerText = "No vehicles found matching your criteria.";
        return;
    } 

    vehicles.forEach(function (vehicle) {
        var card = document.createElement('article');
        card.classList.add('vehicle-card');

        card.innerHTML = `
            <h2>${vehicle.make} ${vehicle.model}</h2>
            <p><strong>Year:</strong> ${vehicle.year}</p>
            <p><strong>Transmission:</strong> ${vehicle.transmission}</p>
            <p><strong>Fuel Type:</strong> ${vehicle.fuelType}</p>
            <p><strong>Price:</strong> £${vehicle.price}</p>
            <p><strong>Engine Size:</strong> ${vehicle.engineSize}</p>
        `;

        card.addEventListener('click', function() {
            openModal(vehicle);
        });

        card.addEventListener('keypress', function (e) {
            if (e.key === 'Enter') {
                openModal(vehicle);
            }
        });

        container.appendChild(card);
    });
}

// Open a modal with extra information about the vehicle when a card is selected.
// The modal is generated by setting the innerHTML of the modal's body and the "hidden" class is removed from the modal to make it visible.

function openModal(vehicle) {
    modalBody.innerHTML = `
        <h2>${vehicle.make} ${vehicle.model}</h2>
        <p>Year: ${vehicle.year}</p>
        <p>Transmission: ${vehicle.transmission}</p>
        <p>Fuel Type: ${vehicle.fuelType}</p>
        <p>Price: £${vehicle.price}</p>
        <p>Mileage: ${vehicle.mileage} miles</p>
        <p>MPG: ${vehicle.mpg}</p>
        <p>Tax: £${vehicle.tax}/year</p>
        <p>Engine Size: ${vehicle.engineSize}L</p>
    `;
    modal.classList.remove('hidden');
}

// Fetches the vehicle data from the JSON file and returns a promise which resolves to the parsed JSON data. The promise is stored in the "vehicles" variable, which is globally accessible.

function getVehicles() {
    return fetch("vehicleStorage.json")
    .then(function (data) {
        return data.json();
    })
}
console.log(vehicles)

// Creates and populates the dropdowns by mapping the vehicle information to an array of the relevant field, converting it to a "Set" to remove duplicates, and then creating an "option" element for each unique value which is then appended to the relevant dropdown container.

function createDropdown(vehicleData, fieldID) {
    vehicleData.then(function (allVehicles) {
        var data = allVehicles.map(function (item) {
            return item[fieldID];
        });
        data = new Set(data);

        var dropdownContainer = document.getElementById(fieldID + 'Filter')
        data.forEach(function (item) {
            var option = document.createElement('option');
            option.value = item;
            option.innerText = item;
            dropdownContainer.appendChild(option);
        });
    })
}

function handleVehicleSearch(e) {
    e.preventDefault();

    vehicles.then(function (allVehicles) {
        searchAndDisplayResults(allVehicles);
        console.log(container)
    });
}

// Filters the information based on the search criteria by checking if the search string is set to "All", and if it is not, the function then checks if the property being filtered is a boolean or a string, where it is then compared to the search string with .toLowerCase() only being applied to string values to avoid errors.

function filterBy(data, searchString, prop) {
    return data.filter(function (item) {
        if (searchString === "All") return true;

        if (typeof(item[prop]) === "boolean") {
            return item[prop] === searchString;
        }

        if (typeof(item[prop]) === "string") {
            return item[prop].toLowerCase() === searchString.toLowerCase();
        }
        return false;
    });
}



function searchAndDisplayResults(vhcs) {
    var chosenMake = vehicleSearchForm.makeFilter.value
    var chosenModel = vehicleSearchForm.modelFilter.value
    var chosenTransmission = vehicleSearchForm.transmissionFilter.value
    var chosenFuelType = vehicleSearchForm.fuelTypeFilter.value

    var vehiclesFound = filterBy(vhcs, chosenMake, "make")
    vehiclesFound = filterBy(vehiclesFound, chosenModel, "model")
    vehiclesFound = filterBy(vehiclesFound, chosenTransmission, "transmission")
    vehiclesFound = filterBy(vehiclesFound, chosenFuelType, "fuelType")
    
    var minYear = Number(document.getElementById('minYear').value) || 0
    var maxYear = Number(document.getElementById('maxYear').value) || Infinity
    vehiclesFound = vehiclesFound.filter(function (item) {
        return item.year >= minYear && item.year <= maxYear
    })

    var minPrice = Number(document.getElementById('minPrice').value) || 0
    var maxPrice = Number(document.getElementById('maxPrice').value) || Infinity
    vehiclesFound = vehiclesFound.filter(function (item) {
        return item.price >= minPrice && item.price <= maxPrice
    })

    var minMileage = Number(document.getElementById('minMileage').value) || 0
    var maxMileage = Number(document.getElementById('maxMileage').value) || Infinity
    vehiclesFound = vehiclesFound.filter(function (item) {
        return item.mileage >= minMileage && item.mileage <= maxMileage
    })

    var minMPG = Number(document.getElementById('minMPG').value) || 0
    var maxMPG = Number(document.getElementById('maxMPG').value) || Infinity
    vehiclesFound = vehiclesFound.filter(function (item) {
        return item.mpg >= minMPG && item.mpg <= maxMPG
    })
    var minTax = Number(document.getElementById('minTax').value) || 0
    var maxTax = Number(document.getElementById('maxTax').value) || Infinity
    vehiclesFound = vehiclesFound.filter(function (item) {
        return item.tax >= minTax && item.tax <= maxTax
    })
    var minEngineSize = Number(document.getElementById('minEngineSize').value) || 0
    var maxEngineSize = Number(document.getElementById('maxEngineSize').value) || Infinity
    vehiclesFound = vehiclesFound.filter(function (item) {
        return item.engineSize >= minEngineSize && item.engineSize <= maxEngineSize
    })

    displayResults(vehiclesFound)
}

// Calls forth the createDropdown function for each of the relevant fields which populates the dropdowns with the relevant information, and adds an event listener to the form which calls for the handleVehicleSearch function when the "submit" event (in the form of a "submit button" is clicked) occurs.

function start() {
    createDropdown(vehicles, "make")
    createDropdown(vehicles, "model")
    createDropdown(vehicles, "transmission")
    createDropdown(vehicles, "fuelType")
    vehicleSearchForm.addEventListener('submit', handleVehicleSearch)

    // Closes the modal when the user clicks the "x" button by adding the "hidden" class to the modal.

    document.getElementById('closeModal').addEventListener('click', function() {
        modal.classList.add('hidden')
    })

    // Closes (or hides) the modal when the user clicks outside of the modal's content area by adding the "hidden" class to the modal.

    window.addEventListener('click', function(event) {
        if (event.target === modal) {
            modal.classList.add('hidden')
        }
    })
}