// Ensures the "start" function is only called for when the page has been fully loaded, if this were not the case, errors may be present as the script may attempt to access elements which have not yet been rendered.

window.addEventListener('load', start)

var vehicleSearchForm = document.forms.vehicleSearchForm // Retrieves the Vehicle Search Form from HTML.
var vehicles = getVehicles(); // Fetches the vehicle information from the JSON file and stores it as a promise.
var container = document.getElementById('display-results') // The container in which the results are displayed on the webpage.
var modal = document.getElementById('modal') // Retrieves the modal from HTML.
var modalBody = document.getElementById('modalBody') // The container in which more detailed information about the vehicle is displayed within the modal element.

// Displays the vehicle results which have been filtered by other functions by creating a card (an "article" element) for each vehicle, which is then populated with the relevant information and appended to the container.
// If no vehicles are found matching the search criteria, a message is displayed notifying the user that none were found matching their criteria.
// Calls for the "openModal" function if a card is clicked on, where a modal is then opened with extra information about the vehicle.
// The "openModal" function can also be called by pressing the "Enter" key when a card is selected, for accessibility purposes.

function displayResults(vehicles) {
    container.innerHTML = ""; // Clears the container of any previously displayed results.

    if (vehicles.length === 0) {
        container.innerText = "No vehicles found matching your criteria.";
        return;
    } 

    vehicles.forEach(function (vehicle) {
        var card = document.createElement('article');
        card.classList.add('vehicle-card');

        card.innerHTML = `
            <h2>${vehicle.make} ${vehicle.model}</h2>
            <p><strong>Year:</strong> ${vehicle.year}</p>
            <p><strong>Transmission:</strong> ${vehicle.transmission}</p>
            <p><strong>Fuel Type:</strong> ${vehicle.fuelType}</p>
            <p><strong>Price:</strong> £${vehicle.price}</p>
            <p><strong>Engine Size:</strong> ${vehicle.engineSize}</p>
        `;

        card.addEventListener('click', function() {
            openModal(vehicle);
        });

        card.addEventListener('keypress', function (e) {
            if (e.key === 'Enter') {
                openModal(vehicle);
            }
        });

        container.appendChild(card); // Appends the 'container' element, which displays the results in the 'display-results' section of the webpage.
    });
}

// Opens a modal with extra information about the vehicle when a card is selected.
// The modal is generated by setting the innerHTML of the modal's body and the "hidden" class is removed from the modal to make it visible.

function openModal(vehicle) {
    modalBody.innerHTML = `
        <h2>${vehicle.make} ${vehicle.model}</h2>
        <p>Year: ${vehicle.year}</p>
        <p>Transmission: ${vehicle.transmission}</p>
        <p>Fuel Type: ${vehicle.fuelType}</p>
        <p>Price: £${vehicle.price}</p>
        <p>Mileage: ${vehicle.mileage} miles</p>
        <p>MPG: ${vehicle.mpg}</p>
        <p>Tax: £${vehicle.tax}/year</p>
        <p>Engine Size: ${vehicle.engineSize}L</p>
    `;
    modal.classList.remove('hidden');
}

// Fetches the vehicle data from the JSON file and returns a promise which resolves to the parsed JSON data. The promise is stored in the "vehicles" variable, which is globally accessible.

function getVehicles() {
    return fetch("vehicleStorage.json")
    .then(function (data) {
        return data.json();
    })
}
console.log(vehicles)

// Creates and populates the dropdowns by mapping the vehicle information to an array of the relevant field, converting it to a "Set" to remove duplicates, and then creating an "option" element for each unique value which is then appended to the relevant dropdown container.

function createDropdown(vehicleData, fieldID) {
    vehicleData.then(function (allVehicles) {
        var data = allVehicles.map(function (item) {
            return item[fieldID];
        });
        data = new Set(data);

        var dropdownContainer = document.getElementById(fieldID + 'Filter')
        data.forEach(function (item) {
            var option = document.createElement('option');
            option.value = item;
            option.innerText = item;
            dropdownContainer.appendChild(option);
        });
    })
}

function handleVehicleSearch(e) {
    e.preventDefault(); // Prevents the default action of submission, which in this instance would refresh the page.

    vehicles.then(function (allVehicles) {
        searchAndDisplayResults(allVehicles);
        console.log(container)
    });
}

// Filters the information based on the search criteria by checking if the search string is set to "All", and if it is not, the function then checks if the property being filtered is a boolean or a string, where it is then compared to the search string, with .toLowerCase() only being applied to string values to avoid errors.

function filterBy(data, searchString, prop) {
    return data.filter(function (item) {
        if (searchString === "All") return true;

        if (typeof(item[prop]) === "boolean") {
            return item[prop] === searchString;
        }

        if (typeof(item[prop]) === "string") {
            return item[prop].toLowerCase() === searchString.toLowerCase();
        }
        return false;
    });
}

// Filters the information based on a range (user-input), used to avoid hard-coding the function and allows the function to be used again in the future if necessary.

function rangeFilter(data, misc) {
    var min = Number(document.getElementById(misc.minID).value) || 0
    var max = Number(document.getElementById(misc.maxID).value) || Infinity

    return data.filter(function (item) {
        return item[misc.prop] >= min && item[misc.prop] <= max
    })
}

// Filters the information based on the searchString, used to avoid hard-coding the function and allows the function to be used again in the future if necessary.

function miscFilter(data, misc) {
    var searchString = document.getElementById(misc.id).value

    return filterBy(data, searchString, misc.prop)
}

function searchAndDisplayResults(vhcs) {

    // Variables for the miscFilter function. An array of objects is used to avoid hard-coding the function and allows for expansion in the future if necessary.
    // If a new range range needs to be added, all that is required is the addition of a new object within the array below.

    var miscFilters = [
        { prop: "make", id: "makeFilter" },
        { prop: "model", id: "modelFilter" },
        { prop: "transmission", id: "transmissionFilter" },
        { prop: "fuelType", id: "fuelTypeFilter" }
    ]

    // Variables for the rangeFilter function. An array of objects is used to avoid hard-coding the function and allows for expansion in the future if necessary.
    // If a new range range needs to be added, all that is required is the addition of a new object within the array below.

    var rangeFilters = [
        { prop: "year", minID: "minYear", maxID: "maxYear" },
        { prop: "price", minID: "minPrice", maxID: "maxPrice" },
        { prop: "mileage", minID: "minMileage", maxID: "maxMileage" },
        { prop: "mpg", minID: "minMPG", maxID: "maxMPG" },
        { prop: "tax", minID: "minTax", maxID: "maxTax" },
        { prop: "engineSize", minID: "minEngineSize", maxID: "maxEngineSize" }
    ]

    var vehiclesFound = vhcs // Creates the variable "vehiclesFound" and populates it with the contents of "vhcs", the list of all the vehicles.

    miscFilters.forEach(function (misc) {
        vehiclesFound = miscFilter(vehiclesFound, misc)
    })

    rangeFilters.forEach(function (misc) {
        vehiclesFound = rangeFilter(vehiclesFound, misc)
    })

    displayResults(vehiclesFound)
}

// Calls forth the createDropdown function for each of the relevant fields which populates the dropdowns with the relevant information, and adds an event listener to the form which calls for the handleVehicleSearch function when the "submit" event (in the form of a "submit button" is clicked) occurs.

function start() {
    createDropdown(vehicles, "make")
    createDropdown(vehicles, "model")
    createDropdown(vehicles, "transmission")
    createDropdown(vehicles, "fuelType")
    vehicleSearchForm.addEventListener('submit', handleVehicleSearch)

    // Closes (or hides) the modal when the user clicks the "x" button by adding the "hidden" class to the modal.

    document.getElementById('closeModal').addEventListener('click', function() {
        modal.classList.add('hidden')
    })

    // Closes (or hides) the modal when the user clicks outside of the modal's content area by adding the "hidden" class to the modal.

    window.addEventListener('click', function(event) {
        if (event.target === modal) {
            modal.classList.add('hidden')
        }
    })
}